"""Forecasting models (roadmap Phase 8) — research-grade, honestly evaluated.

Models here are SHADOW/advisory until they pass out-of-sample evaluation against
strong naive benchmarks; none drives sizing or trading on import. The first is a
HAR-RV volatility forecaster (Corsi 2009) benchmarked against EWMA/RiskMetrics
and a random walk.
"""

from quant.forecast.ensemble import (
    BASE_LEARNERS,
    StackConfig,
    StackEval,
    StackForecast,
    build_base_panel,
    compute_stack,
    fit_stacker,
    live_stack,
    render_stack,
    walk_forward_stack,
)
from quant.forecast.factor import (
    FACTOR_UNIVERSE,
    FactorConfig,
    FactorEval,
    FactorScores,
    compute_factor_scores,
    live_factor_scores,
    render_factor_scores,
    walk_forward_factor_eval,
)
from quant.forecast.regime import (
    BOCPDConfig,
    ChangePointRead,
    MacroRegimeConfig,
    MacroRegimeRead,
    RegimeComparison,
    RegimeMetrics,
    bocpd_run_length,
    build_macro_regime_features,
    change_point_series,
    compare_regime_models,
    compute_change_points,
    compute_macro_regime,
    live_macro_regime,
    render_macro_regime,
)
from quant.forecast.vol import (
    HARModel,
    VolForecast,
    compute_vol_forecast,
    ewma_forecast_series,
    fit_har,
    har_forecast_next,
    live_vol_forecast,
    qlike,
    realized_variance,
    render_vol_forecast,
    walk_forward_eval,
)

__all__ = [
    "BASE_LEARNERS",
    "FACTOR_UNIVERSE",
    "BOCPDConfig",
    "ChangePointRead",
    "FactorConfig",
    "FactorEval",
    "FactorScores",
    "HARModel",
    "MacroRegimeConfig",
    "MacroRegimeRead",
    "RegimeComparison",
    "RegimeMetrics",
    "StackConfig",
    "StackEval",
    "StackForecast",
    "VolForecast",
    "bocpd_run_length",
    "build_base_panel",
    "build_macro_regime_features",
    "change_point_series",
    "compare_regime_models",
    "compute_change_points",
    "compute_factor_scores",
    "compute_macro_regime",
    "compute_stack",
    "compute_vol_forecast",
    "ewma_forecast_series",
    "fit_har",
    "fit_stacker",
    "har_forecast_next",
    "live_factor_scores",
    "live_macro_regime",
    "live_stack",
    "live_vol_forecast",
    "qlike",
    "realized_variance",
    "render_factor_scores",
    "render_macro_regime",
    "render_stack",
    "render_vol_forecast",
    "walk_forward_eval",
    "walk_forward_factor_eval",
    "walk_forward_stack",
]
