# logfilename                                                      [owner:group]      mode count size when flags
/Users/ajaiupadhyaya/Library/Logs/quant-deploy/tick.stdout.log     ajaiupadhyaya:staff 600  7     10000 *    GJ
/Users/ajaiupadhyaya/Library/Logs/quant-deploy/tick.stderr.log     ajaiupadhyaya:staff 600  7     10000 *    GJ
/Users/ajaiupadhyaya/Library/Logs/quant-deploy/guard.stdout.log    ajaiupadhyaya:staff 600  7     10000 *    GJ
/Users/ajaiupadhyaya/Library/Logs/quant-deploy/guard.stderr.log    ajaiupadhyaya:staff 600  7     10000 *    GJ
